POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "sefu",
    "password": "1234"
}


###

POST http://localhost:8080/test
Content-Type: application/json

{
    "username": "sefu",
    "password": "1234"
}
